/**
 * Catálogo de herramientas con metadata orientada al estudiante (UI del portal).
 * @module tools/catalog
 */

export interface ToolStudentDoc {
  id: string;
  name: string;
  category: "examenes" | "notas" | "tps" | "lecturas" | "avisos";
  categoryLabel: string;
  tagColor: "teal" | "amber" | "purple" | "dark";
  summary: string;
  benefit: string;
  examplePrompt: string;
  parametersHint: string;
}

export const TOOLS_CATALOG: ToolStudentDoc[] = [
  {
    id: "s21_check_academic_status",
    name: "Calculadora de Regularidad y Promoción",
    category: "notas",
    categoryLabel: "Notas y Cursada",
    tagColor: "amber",
    summary: "Calcula tu promedio actual y te dice exactamente qué nota necesitas en los próximos TPs para promocionar directo (7+) o quedar regular (5+).",
    benefit: "Evita sorpresas a fin de cursada sabiendo con precisión matemática qué nota necesitas para no rendir final.",
    examplePrompt: "¿Cuál es mi estado académico en la materia con ID 34584 y qué notas necesito en los próximos TPs para promocionar directo?",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_open_interactive_portal",
    name: "Portal Interactivo Unificado Siglo 21",
    category: "notas",
    categoryLabel: "Notas y Cursada",
    tagColor: "teal",
    summary: "Abre el portal interactivo de escritorio con diseño oficial Siglo 21: bienvenida, métricas del alumno, accesos rápidos y documentación interactiva.",
    benefit: "Visualiza todo tu ecosistema universitario y herramientas en un solo lugar sin salir al navegador externo.",
    examplePrompt: "Abre el portal interactivo unificado de Siglo 21.",
    parametersHint: "No requiere parámetros (opcional: port, auto_open)",
  },
  {
    id: "s21_open_exam_simulator",
    name: "Simulador Oficial de Exámenes y APIs",
    category: "examenes",
    categoryLabel: "Exámenes y Práctica",
    tagColor: "teal",
    summary: "Abre el portal interactivo de escritorio directamente en la sección del Simulador para rendir simulacros cronometrados, practicar y consultar notas.",
    benefit: "Entrena con el formato exacto de las APIs y parciales de Siglo 21 antes de rendir.",
    examplePrompt: "Abre el simulador interactivo de exámenes para entrenar mis parciales en la materia 34584.",
    parametersHint: "Opcional: course_id, mode ('exam'/'practice'), start_exam, port, auto_open",
  },
  {
    id: "s21_get_bank_questions",
    name: "Consultor de Preguntas en SQLite",
    category: "examenes",
    categoryLabel: "Exámenes y Práctica",
    tagColor: "teal",
    summary: "Recupera las preguntas guardadas en el banco local de una materia, filtrando opcionalmente por módulo o con límite de cantidad.",
    benefit: "Revisa reactivos existentes, evita preguntas repetidas y repasa explicaciones teóricas.",
    examplePrompt: "¿Qué preguntas tengo cargadas para el Módulo 1 de la materia 34584?",
    parametersHint: "course_id (obligatorio), module_number (opcional), limit (opcional)",
  },
  {
    id: "s21_save_questions_to_bank",
    name: "Cargador Inteligente de Preguntas a SQLite",
    category: "examenes",
    categoryLabel: "Exámenes y Práctica",
    tagColor: "teal",
    summary: "Permite al asistente IA analizar PDFs oficiales y persistir lotes de preguntas de examen categorizadas por módulo y lectura en SQLite local.",
    benefit: "Construye tu propio banco privado de preguntas para cada materia.",
    examplePrompt: "Lee la Lectura 2 de mi materia y guarda 10 preguntas de opción múltiple en el banco de preguntas.",
    parametersHint: "course_id, course_name, questions",
  },
  {
    id: "s21_generate_practice_quiz",
    name: "Generador Rápido de Quizzes",
    category: "examenes",
    categoryLabel: "Exámenes y Práctica",
    tagColor: "teal",
    summary: "Lee la lectura obligatoria oficial de Canvas y crea un prompt y simulacro de preguntas multiple choice con justificación de respuestas.",
    benefit: "Repasa conceptos puntuales directamente en el chat.",
    examplePrompt: "Generame un simulacro de 5 preguntas para el Módulo 1, Lectura 2 de mi materia (course_id: 34584).",
    parametersHint: "ID de materia, número de módulo (1-4), número de lectura (1-4)",
  },
  {
    id: "s21_get_pending_tasks",
    name: "Agenda de Entregas y Vencimientos",
    category: "tps",
    categoryLabel: "Trabajos Prácticos",
    tagColor: "dark",
    summary: "Revisa todas tus materias activas y genera una lista ordenada de TPs y entregas pendientes con la cuenta regresiva de días restantes.",
    benefit: "Nunca más se te va a pasar la fecha límite de un Trabajo Práctico.",
    examplePrompt: "Mostrame todas mis tareas y TPs pendientes de todas las materias ordenadas por fecha de entrega.",
    parametersHint: "No requiere parámetros (revisa todo automáticamente)",
  },
  {
    id: "s21_audit_rubric",
    name: "Auditor de Rúbrica para TPs",
    category: "tps",
    categoryLabel: "Trabajos Prácticos",
    tagColor: "purple",
    summary: "Compara el borrador de tu trabajo contra la rúbrica de corrección que usará el profesor en Canvas y te dice qué corregir para sacar 10.",
    benefit: "Aseguras el cumplimiento punto por punto de cada criterio antes de enviar tu TP.",
    examplePrompt: "Audita este borrador para el TP1 de mi materia contra la rúbrica oficial y decime qué puntos débiles tengo:\n\n[Pega aquí el texto de tu borrador]",
    parametersHint: "ID de materia, ID del trabajo práctico, texto del borrador",
  },
  {
    id: "s21_get_assignments",
    name: "Consignas Claras de Trabajos Prácticos",
    category: "tps",
    categoryLabel: "Trabajos Prácticos",
    tagColor: "dark",
    summary: "Descarga las consignas de los TP1, TP2, TP3 y TP4 en texto limpio y legible, mostrando objetivos, fechas de entrega y rúbricas.",
    benefit: "Lee las consignas sin tablas rotas ni formatos molestos de Canvas.",
    examplePrompt: "Traeme la consigna completa y fecha de entrega del TP1 de la materia 34584.",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_get_reading",
    name: "Buscador Directo de Lecturas SAM",
    category: "lecturas",
    categoryLabel: "Lecturas y PDFs",
    tagColor: "teal",
    summary: "Localiza al instante la lectura o actividad de un módulo específico y descarga o extrae el texto del PDF automáticamente.",
    benefit: "Acceso inmediato al contenido exacto que necesitas estudiar sin buscar carpeta por carpeta.",
    examplePrompt: "Búscame y leé el contenido completo de la Lectura 1 del Módulo 2 del curso 34584.",
    parametersHint: "ID de materia, Módulo (1-4), Lectura (1-4)",
  },
  {
    id: "s21_read_pdf_content",
    name: "Lector Inteligente de Documentos PDF",
    category: "lecturas",
    categoryLabel: "Lecturas y PDFs",
    tagColor: "purple",
    summary: "Descarga y extrae el texto de cualquier PDF o documento subido a Canvas para que puedas pedirle resúmenes, explicaciones o cuadros sinópticos.",
    benefit: "Transforma PDFs largos en explicaciones claras, resúmenes al punto y mapas conceptuales.",
    examplePrompt: "Lee este archivo PDF de Canvas (file_id: 123456) y hazme un resumen en 5 puntos clave de los conceptos principales.",
    parametersHint: "ID de archivo (file_id) o URL de descarga",
  },
  {
    id: "s21_search_readings",
    name: "Buscador de Conceptos en Todos tus Apuntes",
    category: "lecturas",
    categoryLabel: "Lecturas y PDFs",
    tagColor: "amber",
    summary: "Busca un concepto, ley, fórmula o término en todas las lecturas y archivos que tengas guardados en tu espacio de estudio.",
    benefit: "Encuentra en qué módulo y lectura se explicó un tema sin tener que abrir uno por uno.",
    examplePrompt: "Buscá en mis lecturas el concepto 'diagrama de clases UML' y mostrame en qué materias aparece.",
    parametersHint: "Término o consulta (query)",
  },
  {
    id: "s21_list_courses",
    name: "Panel de Mis Materias",
    category: "notas",
    categoryLabel: "Notas y Cursada",
    tagColor: "teal",
    summary: "Lista todas tus materias activas del cuatrimestre o tu historial completo con sus códigos oficiales, IDs y nombres claros.",
    benefit: "Obtén rápidamente los IDs de tus materias para usar en las demás herramientas.",
    examplePrompt: "Listame mis materias activas de este cuatrimestre con sus IDs correspondientes.",
    parametersHint: "Opcional: incluir materias finalizadas, filtrar por nombre",
  },
  {
    id: "s21_get_modules",
    name: "Estructura de Módulos y Unidades SAM",
    category: "lecturas",
    categoryLabel: "Lecturas y PDFs",
    tagColor: "dark",
    summary: "Muestra el mapa curricular completo de la materia: los 4 módulos, sus lecturas, actividades prácticas y materiales complementarios.",
    benefit: "Ten una visión panorámica de todo el temario que entra en la cursada.",
    examplePrompt: "¿Cómo están organizados los 4 módulos de la materia 34584 y qué lecturas tiene cada uno?",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_get_announcements",
    name: "Tablón de Avisos de Profesores",
    category: "avisos",
    categoryLabel: "Comunicación y Avisos",
    tagColor: "amber",
    summary: "Obtiene los últimos anuncios, aclaraciones y avisos que publicaron los docentes y tutores en tus materias.",
    benefit: "Enterate de cambios de fechas, clases de consulta y tips de entrega sin entrar a cada materia.",
    examplePrompt: "Mostrame los últimos avisos y novedades que publicaron los profesores en mis materias.",
    parametersHint: "Opcional: lista de IDs de materias",
  },
  {
    id: "s21_get_upcoming_events",
    name: "Radar de Calendario y Fechas Clave",
    category: "avisos",
    categoryLabel: "Comunicación y Avisos",
    tagColor: "purple",
    summary: "Consulta los eventos agendados, fechas de exámenes parciales, finales y turnos en tu calendario de Canvas.",
    benefit: "Planifica tu semana y mes de estudio con anticipación.",
    examplePrompt: "¿Qué eventos, exámenes o fechas clave tengo agendadas para las próximas semanas?",
    parametersHint: "No requiere parámetros",
  },
  {
    id: "s21_get_discussion_topics",
    name: "Foros de Debate y Actividades Grupales",
    category: "tps",
    categoryLabel: "Trabajos Prácticos",
    tagColor: "teal",
    summary: "Extrae las consignas de los foros de debate del curso, incluyendo los debates obligatorios vinculados al TP2.",
    benefit: "Conoce exactamente qué consigna responder en el foro sin perder tiempo navegando.",
    examplePrompt: "Traeme los foros de debate de la materia 34584 y las consignas de participación.",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_get_syllabus",
    name: "Programa de Materia y Equipo Docente",
    category: "notas",
    categoryLabel: "Notas y Cursada",
    tagColor: "dark",
    summary: "Muestra el programa oficial, objetivos de la materia, criterios de evaluación y datos del equipo docente.",
    benefit: "Revisa qué bibliografía y objetivos rigen tu materia.",
    examplePrompt: "Mostrame el programa general y criterios de evaluación de la materia 34584.",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_get_course_files",
    name: "Biblioteca de Archivos de la Materia",
    category: "lecturas",
    categoryLabel: "Lecturas y PDFs",
    tagColor: "amber",
    summary: "Explora todos los documentos, casos de estudio y archivos adicionales que los docentes compartieron en la materia.",
    benefit: "Encuentra archivos complementarios incluso si la pestaña de archivos tiene acceso restringido.",
    examplePrompt: "Listame todos los archivos y documentos descargables disponibles en la materia 34584.",
    parametersHint: "ID de la materia (course_id)",
  },
  {
    id: "s21_get_my_profile",
    name: "Credencial y Perfil de Estudiante",
    category: "notas",
    categoryLabel: "Notas y Cursada",
    tagColor: "purple",
    summary: "Muestra tu información de usuario conectado a Canvas: nombre completo, correo institucional e ID de estudiante.",
    benefit: "Verifica que tu sesión y token de Canvas estén funcionando correctamente.",
    examplePrompt: "¿Quién es el usuario actualmente conectado en Canvas?",
    parametersHint: "No requiere parámetros",
  },
];
